services:
  postgres-db-users:
    container_name: userPostgresContainer
    image: postgres:16.0
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bigdata
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - '25432:5432'
    volumes:
      - user-db-volume:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  user-db-volume:

networks:
  backend-network:
